name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install molecule
      run: cargo install moleculec@0.7.5 --locked
    - name: Ensure moledule schema changes are committed
      working-directory: ./rust
      run: moleculec --language rust --schema-file ../ts/schemas/basic.mol > src/schemas/basic.rs && moleculec --language rust --schema-file ../ts/schemas/top_level.mol > src/schemas/top_level.rs && cargo fmt && git diff --exit-code
    - name: riscv target
      working-directory: ./rust
      run: rustup target add riscv64imac-unknown-none-elf
    - name: Build
      working-directory: ./rust
      run: cargo build --verbose --target=riscv64imac-unknown-none-elf
